[package]
name = "brs"
version = "0.1.0"
authors = ["ns <portification@gmail.com>"]
edition = "2018"
description = "Read and write Brickadia save files."
readme = "README.md"
keywords = ["brickadia", "parser", "file", "binary", "node", "javascript"]
categories = ["encoding"]
license = "MIT"

[dependencies]
brs = "0.1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.7", features = ["v5", "serde"] }

serde = { version = "^1.0", features = ["derive"] }
wasm-bindgen = {version = "^0.2", features = ["serde-serialize"]}