[package]
name = "brs"
version = "0.1.0"
authors = ["ns <portification@gmail.com>"]
edition = "2018"
description = "Read and write Brickadia save files."
readme = "README.md"
keywords = ["brickadia", "parser", "file", "binary", "node", "javascript"]
categories = ["encoding"]
license = "MIT"

[dependencies]
byteorder = "1"
# libflate = "0.1" # Would not decode when built in WebAssembly
uuid = { version = "0.7", features = ["v5", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
num_enum = "0.2.0"

serde = { version = "^1.0", features = ["derive"] }
wasm-bindgen = {version = "^0.2", features = ["serde-serialize"]}
flate2 = "1.0.14"